# Generated by Django 4.1.3 on 2022-11-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
