# Generated by Django 4.1.3 on 2022-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingitem_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
