# Generated by Django 4.1.3 on 2022-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitemstatus',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meetingitemstatus',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meetingitemstatus',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Development', 'In Development'), ('Awaiting Invoicing', 'Awaiting Invoices'), ('Closed', 'Closed')], max_length=100, null=True),
        ),
    ]
