# Generated by Django 4.1.3 on 2022-11-23 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingitemstatus_count_meetingitemstatus_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
