# Generated by Django 4.1.3 on 2022-11-23 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
