# Generated by Django 4.1.3 on 2022-11-23 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='due_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meetingitem',
            name='person_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='meetings.meeting'),
        ),
    ]
