# Generated by Django 4.1.3 on 2022-11-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meetingitem_due_date_meetingitem_person_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_meeting', to='meetings.meeting')),
                ('meeting_items', models.ManyToManyField(to='meetings.meetingitem')),
            ],
        ),
    ]
