# Generated by Django 4.1.3 on 2022-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meetingitem_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
