# Generated by Django 4.1.3 on 2022-11-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_alter_meetingitem_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
